#CONFIG APPLICATION PORT
server.port = 8080

#CONFIG POOL
spring.datasource.hikari.connectionTiomeout=20000
spring.datasource.hikari.maximumPoolSize=5

#CONFIG DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/UserApi
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_SENHA}

#CONFIG FLYWAY SCHEMAS
spring.flyway.schemas=users
spring.jpa.properties.hibernate.default_schemas=user